// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ChangePassword(ctx context.Context, arg ChangePasswordParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	FindUser(ctx context.Context, id int32) (User, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTodo(ctx context.Context, id int32) (Todo, error)
	GetTodos(ctx context.Context, arg GetTodosParams) ([]Todo, error)
	GetTodosCount(ctx context.Context, userID int32) (int64, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
